[build-system]
requires = ["setuptools>=65.0.0", "wheel>=0.40.0"]
build-backend = "setuptools.build_meta"

[project]
name = "trading-bot-survivor"
version = "1.0.0"
description = "Trading Bot Survivor - $50 to $1000"
requires-python = ">=3.9,<3.10"

[tool.setuptools]
packages = ["modules"]
