services:
  - type: worker
    name: menudito-trading-bot
    env: python
    plan: starter
    autoDeploy: true
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python minimal_working_bot.py --mode=testnet
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: LOG_LEVEL
        value: "INFO"
      - key: GOOGLE_SHEETS_CREDENTIALS
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
    healthCheckPath: ""
    runtime:
      shutdownGracePeriodSeconds: 60 